name: indooratlas_flutter
description: workaround https://github.com/flutter/flutter/issues/63240
version: 0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IAFlutterPlugin
